import { products } from "@/types";

export const Products: products[] = [
  {
    id: "1",
    name: "Teethstr8 Max Vitamizzin 230 Rustic Plastic Knife",
    categories: ["Pulse Oximeters", "Wound Care"],
    tags: ["Novelties", "Sandwiches"],
    sku: "rustic-plastic-knife-30177512",
    brands: ["Pulse Oximeters"],
    details:
      "Et esse velit totam sint repudiandae. Similique architecto qui exercitationem aut ut. Dolores quam eligendi unde omnis. Excepturi aliquam nam delectus consequatur. Et aut asperiores et atque.",
    description:
      "Eos in quidem saepe consequatur. Doloribus vel consequatur hic consequatur. Deserunt eos saepe quasi nam alias.Nihil eos deserunt quod. Illo animi sit est ut. Id laboriosam debitis repellendus inventore sunt. Possimus vero laboriosam dolores ut voluptatem. autem enim omnis debitis suscipit voluptatem. Suscipit aut nam quibusdam perferendis. Sunt nihil officiis perspiciatis.",
    price: 89.99,
    priceDel: 129.99,
    images: [
      "https://demo2.pavothemes.com/pharmo/wp-content/uploads/2024/05/product-18-1.jpg",
      "https://demo2.pavothemes.com/pharmo/wp-content/uploads/2024/05/product-18-2-768x768.jpg",
      "https://demo2.pavothemes.com/pharmo/wp-content/uploads/2024/05/product-18-3-768x768.jpg",
      "https://demo2.pavothemes.com/pharmo/wp-content/uploads/2024/05/product-18-4-768x768.jpg",
    ],
    isNew: true,
    discount: 30,
    rating: 4,
    reviewCount: 125,
    isOnSale: true,
    additional_information: [
      { label: "Weight", content: "86 kg" },
      { label: "Dimensions", content: "4 x 170 x 97 cm" },
      {
        label: "Stand Up	",
        content: "35″L x 24″W x 37-45″H(front to back wheel)",
      },
      { label: "Folded (w/o wheels)", content: "32.5″L x 18.5″W x 16.5″H" },
      { label: "Folded (w/ wheels)", content: "32.5″L x 24″W x 18.5″H" },
      { label: "Door Pass Through", content: "24" },
      { label: "Frame", content: "Aluminum" },
      { label: "Weight (w/o wheels)", content: "20 LBS" },
      { label: "Weight Capacity", content: "60 LBS" },
      { label: "Width", content: "24″" },
      { label: "Handle height (ground to handle)", content: "37-45″" },
      { label: "Wheels", content: "12″ air / wide track slick tread" },
      { label: "Seat back height", content: "21.5″" },
      { label: "color", content: "Black, Purple, Turmeric, Yellow" },
      { label: "Size", content: "100ml, 400ml" },
    ],
    link_preview: "https://www.youtube.com/watch?v=g07sRCEYTrw",
  },
  {
    id: "2",
    name: "Gorgeous Linen Small1104",
    categories: ["Patient Care"],
    details:
      "Alias dolorem blanditiis quasi ullam corrupti assumenda aut. Qui facere sapiente et voluptate id. Vel facere eos esse ut fugit. Qui quae in facilis suscipit amet quia sed quia.",
    description:
      "Eos in quidem saepe consequatur. Doloribus vel consequatur hic consequatur. Deserunt eos saepe quasi nam alias.Nihil eos deserunt quod. Illo animi sit est ut. Id laboriosam debitis repellendus inventore sunt. Possimus vero laboriosam dolores ut voluptatem. autem enim omnis debitis suscipit voluptatem. Suscipit aut nam quibusdam perferendis. Sunt nihil officiis perspiciatis.",
    price: 24.99,
    priceDel: 34.99,
    images: [
      "https://demo2.pavothemes.com/pharmo/wp-content/uploads/2024/05/product-10-1.jpg",
    ],
    discount: 25,
    rating: 5,
    reviewCount: 89,
    tags: [],
    sku: "",
    brands: [],
    additional_information: [
      { label: "Weight", content: "86 kg" },
      { label: "Dimensions", content: "4 x 170 x 97 cm" },
      {
        label: "Stand Up	",
        content: "35″L x 24″W x 37-45″H(front to back wheel)",
      },
      { label: "Folded (w/o wheels)", content: "32.5″L x 18.5″W x 16.5″H" },
      { label: "Folded (w/ wheels)", content: "32.5″L x 24″W x 18.5″H" },
      { label: "Door Pass Through", content: "24" },
      { label: "Frame", content: "Aluminum" },
      { label: "Weight (w/o wheels)", content: "20 LBS" },
      { label: "Weight Capacity", content: "60 LBS" },
      { label: "Width", content: "24″" },
      { label: "Handle height (ground to handle)", content: "37-45″" },
      { label: "Wheels", content: "12″ air / wide track slick tread" },
      { label: "Seat back height", content: "21.5″" },
      { label: "color", content: "Black, Purple, Turmeric, Yellow" },
      { label: "Size", content: "100ml, 400ml" },
    ],
    isNew: true,
  },
  {
    id: "3",
    name: "Lightweight Bronze Hat",
    categories: [" Patient Care"],
    details:
      "Alias dolorem blanditiis quasi ullam corrupti assumenda aut. Qui facere sapiente et voluptate id. Vel facere eos esse ut fugit. Qui quae in facilis suscipit amet quia sed quia.",
    description:
      "Eos in quidem saepe consequatur. Doloribus vel consequatur hic consequatur. Deserunt eos saepe quasi nam alias.Nihil eos deserunt quod. Illo animi sit est ut. Id laboriosam debitis repellendus inventore sunt. Possimus vero laboriosam dolores ut voluptatem. autem enim omnis debitis suscipit voluptatem. Suscipit aut nam quibusdam perferendis. Sunt nihil officiis perspiciatis.",
    price: 19.99,
    images: [
      "https://demo2.pavothemes.com/pharmo/wp-content/uploads/2024/05/product-7-1.jpg",
    ],
    isNew: true,
    rating: 4,
    reviewCount: 42,
    tags: [],
    sku: "",
    brands: [],
    additional_information: [
      { label: "Weight", content: "86 kg" },
      { label: "Dimensions", content: "4 x 170 x 97 cm" },
      {
        label: "Stand Up	",
        content: "35″L x 24″W x 37-45″H(front to back wheel)",
      },
      { label: "Folded (w/o wheels)", content: "32.5″L x 18.5″W x 16.5″H" },
      { label: "Folded (w/ wheels)", content: "32.5″L x 24″W x 18.5″H" },
      { label: "Door Pass Through", content: "24" },
      { label: "Frame", content: "Aluminum" },
      { label: "Weight (w/o wheels)", content: "20 LBS" },
      { label: "Weight Capacity", content: "60 LBS" },
      { label: "Width", content: "24″" },
      { label: "Handle height (ground to handle)", content: "37-45″" },
      { label: "Wheels", content: "12″ air / wide track slick tread" },
      { label: "Seat back height", content: "21.5″" },
      { label: "color", content: "Black, Purple, Turmeric, Yellow" },
      { label: "Size", content: "100ml, 400ml" },
    ],
  },
  {
    id: " 4",
    name: "Fuzalin 300 Pills Synergistic Silk Small1104",
    categories: ["Wound Care"],
    details:
      "Quia enim dignissimos occaecati corporis rerum dolore. Sed quae amet placeat suscipit. Nostrum eum laborum aperiam alias nobis soluta aliquid ut.",
    description:
      "Eos in quidem saepe consequatur. Doloribus vel consequatur hic consequatur. Deserunt eos saepe quasi nam alias.Nihil eos deserunt quod. Illo animi sit est ut. Id laboriosam debitis repellendus inventore sunt. Possimus vero laboriosam dolores ut voluptatem. autem enim omnis debitis suscipit voluptatem. Suscipit aut nam quibusdam perferendis. Sunt nihil officiis perspiciatis.",
    price: 59.99,
    priceDel: 79.99,
    images: [
      "https://demo2.pavothemes.com/pharmo/wp-content/uploads/2024/05/product-17-1.jpg",
    ],
    discount: 20,
    rating: 3,
    reviewCount: 56,
    tags: [],
    sku: "",
    brands: [],
    additional_information: [
      { label: "Weight", content: "86 kg" },
      { label: "Dimensions", content: "4 x 170 x 97 cm" },
      {
        label: "Stand Up	",
        content: "35″L x 24″W x 37-45″H(front to back wheel)",
      },
      { label: "Folded (w/o wheels)", content: "32.5″L x 18.5″W x 16.5″H" },
      { label: "Folded (w/ wheels)", content: "32.5″L x 24″W x 18.5″H" },
      { label: "Door Pass Through", content: "24" },
      { label: "Frame", content: "Aluminum" },
      { label: "Weight (w/o wheels)", content: "20 LBS" },
      { label: "Weight Capacity", content: "60 LBS" },
      { label: "Width", content: "24″" },
      { label: "Handle height (ground to handle)", content: "37-45″" },
      { label: "Wheels", content: "12″ air / wide track slick tread" },
      { label: "Seat back height", content: "21.5″" },
      { label: "color", content: "Black, Purple, Turmeric, Yellow" },
      { label: "Size", content: "100ml, 400ml" },
    ],
  },
  {
    id: "5",
    name: "Practical Wool Computer",
    categories: ["PPE Protection"],
    details:
      "Alias dolorem blanditiis quasi ullam corrupti assumenda aut. Qui facere sapiente et voluptate id. Vel facere eos esse ut fugit. Qui quae in facilis suscipit amet quia sed quia.",
    description:
      "Eos in quidem saepe consequatur. Doloribus vel consequatur hic consequatur. Deserunt eos saepe quasi nam alias.Nihil eos deserunt quod. Illo animi sit est ut. Id laboriosam debitis repellendus inventore sunt. Possimus vero laboriosam dolores ut voluptatem. autem enim omnis debitis suscipit voluptatem. Suscipit aut nam quibusdam perferendis. Sunt nihil officiis perspiciatis.",
    price: 45.0,
    images: [
      "https://demo2.pavothemes.com/pharmo/wp-content/uploads/2024/05/product-11-1.jpg",
    ],
    rating: 4,
    reviewCount: 31,
    tags: [],
    sku: "",
    brands: [],
    additional_information: [
      { label: "Weight", content: "86 kg" },
      { label: "Dimensions", content: "4 x 170 x 97 cm" },
      {
        label: "Stand Up	",
        content: "35″L x 24″W x 37-45″H(front to back wheel)",
      },
      { label: "Folded (w/o wheels)", content: "32.5″L x 18.5″W x 16.5″H" },
      { label: "Folded (w/ wheels)", content: "32.5″L x 24″W x 18.5″H" },
      { label: "Door Pass Through", content: "24" },
      { label: "Frame", content: "Aluminum" },
      { label: "Weight (w/o wheels)", content: "20 LBS" },
      { label: "Weight Capacity", content: "60 LBS" },
      { label: "Width", content: "24″" },
      { label: "Handle height (ground to handle)", content: "37-45″" },
      { label: "Wheels", content: "12″ air / wide track slick tread" },
      { label: "Seat back height", content: "21.5″" },
      { label: "color", content: "Black, Purple, Turmeric, Yellow" },
      { label: "Size", content: "100ml, 400ml" },
    ],
  },
];
