import { EmployerCompany, RealEstateItem } from "@/types/real-estate";

export const employerCompanies: EmployerCompany[] = [
  {
    id: 1,
    name: "شركة الأمان العقارية",
    logo: "/logos/aman.png",
    phone: "01001234567",
    email: "info@amanestate.com",
    address: "شارع التسعين، القاهرة الجديدة",
    website: "https://amanestate.com",
  },
  {
    id: 2,
    name: "مجموعة العمران",
    logo: "/logos/omran.png",
    phone: "01111222333",
    email: "sales@omran.com",
    address: "الشيخ زايد، الجيزة",
    website: "https://omran.com",
  },
];

export const realEstateData: RealEstateItem[] = [
  {
    id: 1,
    title: "شقة للبيع في التجمع الخامس",
    location: "التجمع الخامس، القاهرة",
    price: 3500000,
    area: 150,
    bedrooms: 3,
    images: [
      "https://images.bayut.eg/thumbnails/27880446-800x600.webp",
      "https://images.bayut.eg/thumbnails/27880449-800x600.webp",
    ],
    status: "مميز",
    description:
      "شقة مميزة بموقع استراتيجي في قلب التجمع الخامس، تشطيب سوبر لوكس",
    bathrooms: 2,
    yearBuilt: 2020,
    amenities: ["جراج", "أمن 24 ساعة", "انترنت فايبر"],
    type: "فيلا",
    employer: employerCompanies[0],
    downPayment: 2000000,
  },
  {
    id: 2,
    title: "فيلا فاخرة في الشيخ زايد",
    location: "الشيخ زايد، الجيزة",
    price: 8500000,
    area: 280,
    bedrooms: 5,
    images: [
      "https://images.bayut.eg/thumbnails/27878823-800x600.webp",
      "https://images.bayut.eg/thumbnails/27878826-800x600.webp",
    ],
    status: "مميز",
    description: "فيلا مستقلة بحديقة خاصة وحمام سباحة، مساحة كبيرة وتشطيب فاخر",
    bathrooms: 4,
    yearBuilt: 2018,
    amenities: ["مسبح", "حديقة", "جيم", "أمن 24 ساعة"],
    type: "فيلا",
    employer: employerCompanies[1],
    downPayment: 2000000,
  },
  {
    id: 3,
    title: "أرض سكنية في الساحل الشمالي",
    location: "الساحل الشمالي",
    price: 2500000,
    area: 400,
    bedrooms: 0,
    images: [
      "https://images.bayut.eg/thumbnails/27877851-800x600.webp",
      "https://images.bayut.eg/thumbnails/27877854-800x600.webp",
    ],
    status: "مميز",
    description:
      "أرض سكنية مميزة في أفضل مواقع الساحل الشمالي، مؤهلة للبناء الفوري",
    bathrooms: 0,
    yearBuilt: null,
    amenities: [],
    type: "فيلا",
    employer: employerCompanies[1],
    downPayment: 2000000,
  },
  {
    id: 4,
    title: "شقة تمليك في مدينة نصر",
    location: "مدينة نصر، القاهرة",
    price: 2200000,
    area: 120,
    bedrooms: 2,
    images: [
      "https://images.bayut.eg/thumbnails/27873182-800x600.webp",
      "https://images.bayut.eg/thumbnails/27873183-800x600.webp",
    ],
    status: "مميز",
    description: "شقة بالدور الثامن بإطلالة مميزة، تشطيب سوبر لوكس",
    bathrooms: 2,
    yearBuilt: 2015,
    amenities: ["جراج", "أمن 24 ساعة"],
    type: "فيلا",
    employer: employerCompanies[0],
    downPayment: 2000000,
  },
  {
    id: 5,
    title: "عمارة كاملة للبيع في الدقي",
    location: "الدقي، الجيزة",
    price: 12000000,
    area: 600,
    bedrooms: 12,
    images: [
      "https://images.bayut.eg/thumbnails/27873185-800x600.webp",
      "https://images.bayut.eg/thumbnails/27873187-800x600.webp",
    ],
    status: "مميز",
    description: "عمارة سكنية تتكون من 4 شقق بمساحة كل شقة 150م، موقع مميز",
    bathrooms: 8,
    yearBuilt: 2010,
    amenities: ["جراج", "أمن 24 ساعة", "مصعد"],
    type: "فيلا",
    employer: employerCompanies[0],
    downPayment: 2000000,
  },
  {
    id: 6,
    title: "شقة للإيجار في التجمع الخامس",
    location: "التجمع الخامس، القاهرة",
    area: 150,
    bedrooms: 3,
    bathrooms: 2,
    images: [
      "https://images.bayut.eg/thumbnails/27872413-800x600.webp",
      "https://images.bayut.eg/thumbnails/27872414-800x600.webp",
    ],
    status: "مميز",
    description: "شقة مفروشة للإيجار بتشطيب سوبر لوكس وخدمات متكاملة",
    yearBuilt: 2020,
    amenities: ["جراج", "أمن 24 ساعة", "انترنت فايبر"],
    type: "شقة",
    employer: employerCompanies[0],
    rentalTerm: "يومي",
    dayRent: 600,
    weeklyRent: 3800,
    monthlyRent: 14000,
    yearlyRent: 150000,
  },
  {
    id: 7,
    title: "فيلا للإيجار في الشيخ زايد",
    location: "الشيخ زايد، الجيزة",
    area: 280,
    bedrooms: 5,
    bathrooms: 4,
    images: [
      "https://images.bayut.eg/thumbnails/26656120-800x600.webp",
      "https://images.bayut.eg/thumbnails/26656123-800x600.webp",
    ],
    status: "مميز",
    description: "فيلا فاخرة بحديقة ومسبح خاص وتشطيب راقٍ للإيجار",
    yearBuilt: 2018,
    amenities: ["مسبح", "حديقة", "جيم", "أمن 24 ساعة"],
    type: "فيلا",
    employer: employerCompanies[1],
    rentalTerm: "شهري",
    dayRent: 2500,
    weeklyRent: 16000,
    monthlyRent: 55000,
    yearlyRent: 600000,
  },
  {
    id: 8,
    title: "أرض للإيجار في الساحل الشمالي",
    location: "الساحل الشمالي",
    area: 400,
    bedrooms: 0,
    bathrooms: 0,
    images: [
      "https://images.bayut.eg/thumbnails/27854743-800x600.webp",
      "https://images.bayut.eg/thumbnails/27855164-800x600.webp",
    ],
    status: "مميز",
    description: "أرض للإيجار مناسبة لمشاريع سياحية مؤقتة",
    yearBuilt: null,
    amenities: [],
    type: "أرض",
    employer: employerCompanies[1],
    rentalTerm: "شهري",
    dayRent: 1000,
    weeklyRent: 6500,
    monthlyRent: 20000,
    yearlyRent: 220000,
  },
  {
    id: 9,
    title: "شقة للإيجار في مدينة نصر",
    location: "مدينة نصر، القاهرة",
    area: 120,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.bayut.eg/thumbnails/27844164-800x600.webp",
      "https://images.bayut.eg/thumbnails/27844166-800x600.webp",
    ],
    status: "مميز",
    description: "شقة للإيجار مفروشة بالكامل بالقرب من المواصلات والخدمات",
    yearBuilt: 2015,
    amenities: ["جراج", "أمن 24 ساعة"],
    type: "شقة",
    employer: employerCompanies[0],
    rentalTerm: "شهري",
    dayRent: 450,
    weeklyRent: 2800,
    monthlyRent: 9000,
    yearlyRent: 100000,
  },
];
