import { EmployerCompany, RealEstateItem } from "@/types/real-estate";

export const employerCompanies: EmployerCompany[] = [
  {
    id: 1,
    name: "شركة الأمان العقارية",
    logo: "/logos/aman.png",
    phone: "01001234567",
    email: "info@amanestate.com",
    address: "شارع التسعين، القاهرة الجديدة",
    website: "https://amanestate.com",
  },
  {
    id: 2,
    name: "مجموعة العمران",
    logo: "/logos/omran.png",
    phone: "01111222333",
    email: "sales@omran.com",
    address: "الشيخ زايد، الجيزة",
    website: "https://omran.com",
  },
];

export const realEstateData: RealEstateItem[] = [
  {
    id: 1,
    title: "شقة للبيع في التجمع الخامس",
    location: "التجمع الخامس، القاهرة",
    price: 3500000,
    area: 150,
    bedrooms: 3,
    images: [
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
    ],
    status: "مميز",
    description:
      "شقة مميزة بموقع استراتيجي في قلب التجمع الخامس، تشطيب سوبر لوكس",
    bathrooms: 2,
    yearBuilt: 2020,
    amenities: ["جراج", "أمن 24 ساعة", "انترنت فايبر"],
    type: "فيلا",
    employer: employerCompanies[0],
    downPayment: 2000000,
  },
  {
    id: 2,
    title: "فيلا فاخرة في الشيخ زايد",
    location: "الشيخ زايد، الجيزة",
    price: 8500000,
    area: 280,
    bedrooms: 5,
    images: [
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
    ],
    status: "مميز",
    description: "فيلا مستقلة بحديقة خاصة وحمام سباحة، مساحة كبيرة وتشطيب فاخر",
    bathrooms: 4,
    yearBuilt: 2018,
    amenities: ["مسبح", "حديقة", "جيم", "أمن 24 ساعة"],
    type: "فيلا",
    employer: employerCompanies[1],
    downPayment: 2000000,
  },
  {
    id: 3,
    title: "أرض سكنية في الساحل الشمالي",
    location: "الساحل الشمالي",
    price: 2500000,
    area: 400,
    bedrooms: 0,
    images: [
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
    ],
    status: "مميز",
    description:
      "أرض سكنية مميزة في أفضل مواقع الساحل الشمالي، مؤهلة للبناء الفوري",
    bathrooms: 0,
    yearBuilt: null,
    amenities: [],
    type: "فيلا",
    employer: employerCompanies[1],
    downPayment: 2000000,
  },
  {
    id: 4,
    title: "شقة تمليك في مدينة نصر",
    location: "مدينة نصر، القاهرة",
    price: 2200000,
    area: 120,
    bedrooms: 2,
    images: [
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
    ],
    status: "مميز",
    description: "شقة بالدور الثامن بإطلالة مميزة، تشطيب سوبر لوكس",
    bathrooms: 2,
    yearBuilt: 2015,
    amenities: ["جراج", "أمن 24 ساعة"],
    type: "فيلا",
    employer: employerCompanies[0],
    downPayment: 2000000,
  },
  {
    id: 5,
    title: "عمارة كاملة للبيع في الدقي",
    location: "الدقي، الجيزة",
    price: 12000000,
    area: 600,
    bedrooms: 12,
    images: [
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
    ],
    status: "مميز",
    description: "عمارة سكنية تتكون من 4 شقق بمساحة كل شقة 150م، موقع مميز",
    bathrooms: 8,
    yearBuilt: 2010,
    amenities: ["جراج", "أمن 24 ساعة", "مصعد"],
    type: "فيلا",
    employer: employerCompanies[0],
    downPayment: 2000000,
  },
  {
    id: 6,
    title: "شاليه في العين السخنة",
    location: "العين السخنة",
    price: 1800000,
    area: 90,
    bedrooms: 2,
    images: [
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
    ],
    status: "افضل عقار لهذا الاسبوع",
    description: "شاليه في كمبوند سياحي فاخر، إطلالة مباشرة على البحر",
    bathrooms: 1,
    yearBuilt: 2019,
    amenities: ["مسبح", "حديقة", "أمن 24 ساعة"],
    type: "فيلا",
    employer: employerCompanies[0],
    downPayment: 2000000,
  },
  {
    id: 7,
    title: "شقة في كمبوند لافونتين",
    location: "6 أكتوبر، الجيزة",
    price: 4200000,
    area: 180,
    bedrooms: 3,
    images: [
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
    ],
    status: "افضل عقار لهذا الاسبوع",
    description: "شقة في كمبوند لافونتين بمساحة 180م، تشطيب فاخر",
    bathrooms: 3,
    yearBuilt: 2021,
    amenities: ["مسبح", "جيم", "حديقة", "أمن 24 ساعة"],
    type: "فيلا",
    employer: employerCompanies[0],
    downPayment: 2000000,
  },
  {
    id: 8,
    title: "أرض تجارية في المعادي",
    location: "المعادي، القاهرة",
    price: 5000000,
    area: 300,
    bedrooms: 0,
    images: [
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
    ],
    status: "افضل عقار لهذا الاسبوع",
    description:
      "أرض تجارية بموقع مميز على كورنيش المعادي، مؤهلة لمشاريع استثمارية",
    bathrooms: 0,
    yearBuilt: null,
    amenities: [],
    type: "فيلا",
    employer: employerCompanies[0],
    downPayment: 2000000,
  },
  {
    id: 9,
    title: "شقة في كمبوند بيفرلي هيلز",
    location: "الشيخ زايد، الجيزة",
    price: 5500000,
    area: 200,
    bedrooms: 4,
    images: [
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
    ],
    status: "استثنائي",
    description:
      "شقة دوبلكس في كمبوند بيفرلي هيلز، إطلالة خضراء، تشطيب سوبر لوكس",
    bathrooms: 3,
    yearBuilt: 2022,
    amenities: ["مسبح", "جيم", "حديقة", "أمن 24 ساعة", "جراج"],
    type: "فيلا",
    employer: employerCompanies[0],
    downPayment: 2000000,
  },
  {
    id: 10,
    title: "فيلا في كمبوند بلو بلازا",
    location: "العبور، القاهرة",
    price: 9500000,
    area: 350,
    bedrooms: 6,
    images: [
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
      "https://images.bayut.eg/thumbnails/27841531-800x600.webp",
    ],
    status: "استثنائي",
    description:
      "فيلا فاخرة في كمبوند بلو بلازا، مساحة 350م، حديقة خاصة وحمام سباحة",
    bathrooms: 5,
    yearBuilt: 2020,
    amenities: ["مسبح", "حديقة", "جيم", "أمن 24 ساعة", "جراج"],
    type: "فيلا",
    employer: employerCompanies[0],
    downPayment: 2000000,
  },
];
