import { EmployerCompany, RealEstateItem } from "@/types/real-estate";

export const employerCompanies: EmployerCompany[] = [
  {
    id: 1,
    name: "manar ahmed",
    logo: "https://img.freepik.com/free-photo/stylish-confident-businesswoman-smiling_176420-19466.jpg?t=st=1751469075~exp=1751472675~hmac=01ac65af32ee7816fe03acf9b68cf5c617ebdbb1d7d061ef814ff9238b1184fa&w=1380",
    phone: "01001234567",
    email: "info@amanestate.com",
    address: "شارع التسعين، القاهرة الجديدة",
    website: "https://amanestate.com",
    company: "Element Real Estate",
    rating: 5,
    reviews: 45,
  },
  {
    id: 2,
    name: "salma ahmed",
    logo: "https://img.freepik.com/free-photo/stylish-confident-businesswoman-smiling_176420-19466.jpg?t=st=1751469075~exp=1751472675~hmac=01ac65af32ee7816fe03acf9b68cf5c617ebdbb1d7d061ef814ff9238b1184fa&w=1380",
    phone: "01111222333",
    email: "sales@omran.com",
    address: "الشيخ زايد، الجيزة",
    website: "https://omran.com",
    company: "Element Real Estate",
    rating: 4,
    reviews: 77,
  },
];

export const realEstateData: RealEstateItem[] = [
  {
    id: "1",
    title: "شقة للبيع في التجمع الخامس",
    location: {
      lat: 31.0419,
      lng: 29.7433,
      address: "بورتو مارينا، الإسكندرية، مصر",
    },
    nearbyPlaces: [
      {
        id: "1",
        name: "مدرسة بورتو مارينا الدولية",
        type: "school",
        distance: "1.2 كم",
        location: [31.0425, 29.745],
      },
      {
        id: "2",
        name: "مطعم البحر الأحمر",
        type: "restaurant",
        distance: "0.2 كم",
        location: [31.0415, 29.744],
      },
      {
        id: "3",
        name: "مستشفى مارينا الدولي",
        type: "hospital",
        distance: "3 كم",
        location: [31.045, 29.75],
      },
      {
        id: "4",
        name: "سوق بورتو",
        type: "market",
        distance: "0.3 كم",
        location: [31.041, 29.743],
      },
      {
        id: "5",
        name: "شاطئ بورتو",
        type: "beach",
        distance: "0.1 كم",
        location: [31.0418, 29.7445],
      },
    ],
    price: 3500000,
    area: 150,
    bedrooms: 3,
    images: [
      "https://images.bayut.eg/thumbnails/27880446-800x600.webp",
      "https://images.bayut.eg/thumbnails/27880449-800x600.webp",
      "https://images.bayut.eg/thumbnails/27891665-800x600.webp",
      "https://images.bayut.eg/thumbnails/27891666-800x600.webp",
      "https://images.bayut.eg/thumbnails/27891668-800x600.webp",
      "https://images.bayut.eg/thumbnails/27891671-800x600.webp",
    ],
    status: "مميز",
    description:
      "شقة مميزة بموقع استراتيجي في قلب التجمع الخامس، تشطيب سوبر لوكس",
    bathrooms: 2,
    yearBuilt: 2020,
    amenities: ["جراج", "أمن 24 ساعة", "انترنت فايبر"],
    type: "فيلا",
    agent: employerCompanies[0],
    downPayment: 2000000,
    address: "التجمع الخامس، القاهرة الجديدة، القاهرة",
    purpose: "بيع",
    details: {
      bedrooms: 5,
      bathrooms: 4,
      area: 320,
      parking: 2,
      yearBuilt: 2020,
    },

    videos: [
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
    ],
    construction: "جاهز",
    furnishing: "مفروشة",
    createdAt: "2025-07-01T14:20:00Z",
  },
  {
    id: "2",
    title: "فيلا فاخرة في الشيخ زايد",
    location: {
      lat: 31.0419,
      lng: 29.7433,
      address: "بورتو مارينا، الإسكندرية، مصر",
    },
    nearbyPlaces: [
      {
        id: "1",
        name: "مدرسة بورتو مارينا الدولية",
        type: "school",
        distance: "1.2 كم",
        location: [31.0425, 29.745],
      },
      {
        id: "2",
        name: "مطعم البحر الأحمر",
        type: "restaurant",
        distance: "0.2 كم",
        location: [31.0415, 29.744],
      },
      {
        id: "3",
        name: "مستشفى مارينا الدولي",
        type: "hospital",
        distance: "3 كم",
        location: [31.045, 29.75],
      },
      {
        id: "4",
        name: "سوق بورتو",
        type: "market",
        distance: "0.3 كم",
        location: [31.041, 29.743],
      },
      {
        id: "5",
        name: "شاطئ بورتو",
        type: "beach",
        distance: "0.1 كم",
        location: [31.0418, 29.7445],
      },
    ],
    price: 8500000,
    area: 280,
    bedrooms: 5,
    images: [
      "https://images.bayut.eg/thumbnails/27878823-800x600.webp",
      "https://images.bayut.eg/thumbnails/27878826-800x600.webp",
    ],
    status: "مميز",
    description: "فيلا مستقلة بحديقة خاصة وحمام سباحة، مساحة كبيرة وتشطيب فاخر",
    bathrooms: 4,
    yearBuilt: 2018,
    amenities: ["مسبح", "حديقة", "جيم", "أمن 24 ساعة"],
    type: "فيلا",
    agent: employerCompanies[1],
    downPayment: 2000000,
    address: "التجمع الخامس، القاهرة الجديدة، القاهرة",
    purpose: "بيع",
    details: {
      bedrooms: 5,
      bathrooms: 4,
      area: 320,
      parking: 2,
      yearBuilt: 2020,
    },

    videos: [
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
    ],
    construction: "جاهز",
    furnishing: "مفروشة",
    createdAt: "2025-07-01T14:20:00Z",
    reference_num: "بيوت - christine-masaya",
  },
  {
    id: "3",
    title: "أرض سكنية في الساحل الشمالي",
    location: {
      lat: 31.0419,
      lng: 29.7433,
      address: "بورتو مارينا، الإسكندرية، مصر",
    },
    nearbyPlaces: [
      {
        id: "1",
        name: "مدرسة بورتو مارينا الدولية",
        type: "school",
        distance: "1.2 كم",
        location: [31.0425, 29.745],
      },
      {
        id: "2",
        name: "مطعم البحر الأحمر",
        type: "restaurant",
        distance: "0.2 كم",
        location: [31.0415, 29.744],
      },
      {
        id: "3",
        name: "مستشفى مارينا الدولي",
        type: "hospital",
        distance: "3 كم",
        location: [31.045, 29.75],
      },
      {
        id: "4",
        name: "سوق بورتو",
        type: "market",
        distance: "0.3 كم",
        location: [31.041, 29.743],
      },
      {
        id: "5",
        name: "شاطئ بورتو",
        type: "beach",
        distance: "0.1 كم",
        location: [31.0418, 29.7445],
      },
    ],
    price: 2500000,
    area: 400,
    bedrooms: 0,
    images: [
      "https://images.bayut.eg/thumbnails/27877851-800x600.webp",
      "https://images.bayut.eg/thumbnails/27877854-800x600.webp",
    ],
    status: "مميز",
    description:
      "أرض سكنية مميزة في أفضل مواقع الساحل الشمالي، مؤهلة للبناء الفوري",
    bathrooms: 0,
    yearBuilt: null,
    amenities: [],
    type: "فيلا",
    agent: employerCompanies[1],
    downPayment: 2000000,
    address: "التجمع الخامس، القاهرة الجديدة، القاهرة",
    purpose: "بيع",
    details: {
      bedrooms: 5,
      bathrooms: 4,
      area: 320,
      parking: 2,
      yearBuilt: 2020,
    },

    videos: [
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
    ],
    construction: "جاهز",
    furnishing: "مفروشة",
    createdAt: "2025-07-01T14:20:00Z",
    reference_num: "بيوت - christine-masaya",
  },
  {
    id: "4",
    title: "شقة تمليك في مدينة نصر",
    location: {
      lat: 31.0419,
      lng: 29.7433,
      address: "بورتو مارينا، الإسكندرية، مصر",
    },
    nearbyPlaces: [
      {
        id: "1",
        name: "مدرسة بورتو مارينا الدولية",
        type: "school",
        distance: "1.2 كم",
        location: [31.0425, 29.745],
      },
      {
        id: "2",
        name: "مطعم البحر الأحمر",
        type: "restaurant",
        distance: "0.2 كم",
        location: [31.0415, 29.744],
      },
      {
        id: "3",
        name: "مستشفى مارينا الدولي",
        type: "hospital",
        distance: "3 كم",
        location: [31.045, 29.75],
      },
      {
        id: "4",
        name: "سوق بورتو",
        type: "market",
        distance: "0.3 كم",
        location: [31.041, 29.743],
      },
      {
        id: "5",
        name: "شاطئ بورتو",
        type: "beach",
        distance: "0.1 كم",
        location: [31.0418, 29.7445],
      },
    ],
    price: 2200000,
    area: 120,
    bedrooms: 2,
    images: [
      "https://images.bayut.eg/thumbnails/27873182-800x600.webp",
      "https://images.bayut.eg/thumbnails/27873183-800x600.webp",
    ],
    status: "مميز",
    description: "شقة بالدور الثامن بإطلالة مميزة، تشطيب سوبر لوكس",
    bathrooms: 2,
    yearBuilt: 2015,
    amenities: ["جراج", "أمن 24 ساعة"],
    type: "فيلا",
    agent: employerCompanies[0],
    downPayment: 2000000,
    address: "التجمع الخامس، القاهرة الجديدة، القاهرة",
    purpose: "بيع",
    details: {
      bedrooms: 5,
      bathrooms: 4,
      area: 320,
      parking: 2,
      yearBuilt: 2020,
    },

    videos: [
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
    ],
    construction: "جاهز",
    furnishing: "مفروشة",
    createdAt: "2025-07-01T14:20:00Z",
    reference_num: "بيوت - christine-masaya",
  },
  {
    id: "5",
    title: "عمارة كاملة للبيع في الدقي",
    location: {
      lat: 31.0419,
      lng: 29.7433,
      address: "بورتو مارينا، الإسكندرية، مصر",
    },
    nearbyPlaces: [
      {
        id: "1",
        name: "مدرسة بورتو مارينا الدولية",
        type: "school",
        distance: "1.2 كم",
        location: [31.0425, 29.745],
      },
      {
        id: "2",
        name: "مطعم البحر الأحمر",
        type: "restaurant",
        distance: "0.2 كم",
        location: [31.0415, 29.744],
      },
      {
        id: "3",
        name: "مستشفى مارينا الدولي",
        type: "hospital",
        distance: "3 كم",
        location: [31.045, 29.75],
      },
      {
        id: "4",
        name: "سوق بورتو",
        type: "market",
        distance: "0.3 كم",
        location: [31.041, 29.743],
      },
      {
        id: "5",
        name: "شاطئ بورتو",
        type: "beach",
        distance: "0.1 كم",
        location: [31.0418, 29.7445],
      },
    ],
    price: 12000000,
    area: 600,
    bedrooms: 12,
    images: [
      "https://images.bayut.eg/thumbnails/27873185-800x600.webp",
      "https://images.bayut.eg/thumbnails/27873187-800x600.webp",
    ],
    status: "مميز",
    description: "عمارة سكنية تتكون من 4 شقق بمساحة كل شقة 150م، موقع مميز",
    bathrooms: 8,
    yearBuilt: 2010,
    amenities: [
      "جراج",
      "أمن 24 ساعة",
      "مصعد",
      "مصعد",
      "مصعد",
      "مصعد",
      "مصعد",
      "مصعد",
      "مصعد",
    ],
    type: "فيلا",
    agent: employerCompanies[0],
    downPayment: 2000000,
    address: "التجمع الخامس، القاهرة الجديدة، القاهرة",
    purpose: "بيع",
    details: {
      bedrooms: 5,
      bathrooms: 4,
      area: 320,
      parking: 2,
      yearBuilt: 2020,
    },

    videos: [
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
    ],
    construction: "جاهز",
    furnishing: "مفروشة",
    createdAt: "2025-07-01T14:20:00Z",
    reference_num: "بيوت - christine-masaya",
  },
  {
    id: "6",
    title: "شقة للإيجار في التجمع الخامس",
    location: {
      lat: 31.0419,
      lng: 29.7433,
      address: "بورتو مارينا، الإسكندرية، مصر",
    },
    nearbyPlaces: [
      {
        id: "1",
        name: "مدرسة بورتو مارينا الدولية",
        type: "school",
        distance: "1.2 كم",
        location: [31.0425, 29.745],
      },
      {
        id: "2",
        name: "مطعم البحر الأحمر",
        type: "restaurant",
        distance: "0.2 كم",
        location: [31.0415, 29.744],
      },
      {
        id: "3",
        name: "مستشفى مارينا الدولي",
        type: "hospital",
        distance: "3 كم",
        location: [31.045, 29.75],
      },
      {
        id: "4",
        name: "سوق بورتو",
        type: "market",
        distance: "0.3 كم",
        location: [31.041, 29.743],
      },
      {
        id: "5",
        name: "شاطئ بورتو",
        type: "beach",
        distance: "0.1 كم",
        location: [31.0418, 29.7445],
      },
    ],
    area: 150,
    bedrooms: 3,
    bathrooms: 2,
    images: [
      "https://images.bayut.eg/thumbnails/27872413-800x600.webp",
      "https://images.bayut.eg/thumbnails/27872414-800x600.webp",
    ],
    status: "مميز",
    description: "شقة مفروشة للإيجار بتشطيب سوبر لوكس وخدمات متكاملة",
    yearBuilt: 2020,
    amenities: ["جراج", "أمن 24 ساعة", "انترنت فايبر"],
    type: "شقة",
    agent: employerCompanies[0],
    rentalTerm: "يومي",
    dayRent: 600,
    weeklyRent: 3800,
    monthlyRent: 14000,
    yearlyRent: 150000,
    address: "التجمع الخامس، القاهرة الجديدة، القاهرة",
    purpose: "بيع",
    details: {
      bedrooms: 5,
      bathrooms: 4,
      area: 320,
      parking: 2,
      yearBuilt: 2020,
    },

    videos: [
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
    ],
    construction: "جاهز",
    furnishing: "مفروشة",
    createdAt: "2025-07-01T14:20:00Z",
    reference_num: "بيوت - christine-masaya",
  },
  {
    id: "7",
    title: "فيلا للإيجار في الشيخ زايد",
    location: {
      lat: 31.0419,
      lng: 29.7433,
      address: "بورتو مارينا، الإسكندرية، مصر",
    },
    nearbyPlaces: [
      {
        id: "1",
        name: "مدرسة بورتو مارينا الدولية",
        type: "school",
        distance: "1.2 كم",
        location: [31.0425, 29.745],
      },
      {
        id: "2",
        name: "مطعم البحر الأحمر",
        type: "restaurant",
        distance: "0.2 كم",
        location: [31.0415, 29.744],
      },
      {
        id: "3",
        name: "مستشفى مارينا الدولي",
        type: "hospital",
        distance: "3 كم",
        location: [31.045, 29.75],
      },
      {
        id: "4",
        name: "سوق بورتو",
        type: "market",
        distance: "0.3 كم",
        location: [31.041, 29.743],
      },
      {
        id: "5",
        name: "شاطئ بورتو",
        type: "beach",
        distance: "0.1 كم",
        location: [31.0418, 29.7445],
      },
    ],
    area: 280,
    bedrooms: 5,
    bathrooms: 4,
    images: [
      "https://images.bayut.eg/thumbnails/26656120-800x600.webp",
      "https://images.bayut.eg/thumbnails/26656123-800x600.webp",
    ],
    status: "مميز",
    description: "فيلا فاخرة بحديقة ومسبح خاص وتشطيب راقٍ للإيجار",
    yearBuilt: 2018,
    amenities: ["مسبح", "حديقة", "جيم", "أمن 24 ساعة"],
    type: "فيلا",
    agent: employerCompanies[1],
    rentalTerm: "شهري",
    dayRent: 2500,
    weeklyRent: 16000,
    monthlyRent: 55000,
    yearlyRent: 600000,
    address: "التجمع الخامس، القاهرة الجديدة، القاهرة",
    purpose: "بيع",
    details: {
      bedrooms: 5,
      bathrooms: 4,
      area: 320,
      parking: 2,
      yearBuilt: 2020,
    },

    videos: [
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
    ],
    construction: "جاهز",
    furnishing: "مفروشة",
    createdAt: "2025-07-01T14:20:00Z",
    reference_num: "بيوت - christine-masaya",
  },
  {
    id: "8",
    title: "أرض للإيجار في الساحل الشمالي",
    location: {
      lat: 31.0419,
      lng: 29.7433,
      address: "بورتو مارينا، الإسكندرية، مصر",
    },
    nearbyPlaces: [
      {
        id: "1",
        name: "مدرسة بورتو مارينا الدولية",
        type: "school",
        distance: "1.2 كم",
        location: [31.0425, 29.745],
      },
      {
        id: "2",
        name: "مطعم البحر الأحمر",
        type: "restaurant",
        distance: "0.2 كم",
        location: [31.0415, 29.744],
      },
      {
        id: "3",
        name: "مستشفى مارينا الدولي",
        type: "hospital",
        distance: "3 كم",
        location: [31.045, 29.75],
      },
      {
        id: "4",
        name: "سوق بورتو",
        type: "market",
        distance: "0.3 كم",
        location: [31.041, 29.743],
      },
      {
        id: "5",
        name: "شاطئ بورتو",
        type: "beach",
        distance: "0.1 كم",
        location: [31.0418, 29.7445],
      },
    ],
    area: 400,
    bedrooms: 0,
    bathrooms: 0,
    images: [
      "https://images.bayut.eg/thumbnails/27854743-800x600.webp",
      "https://images.bayut.eg/thumbnails/27855164-800x600.webp",
    ],
    status: "مميز",
    description: "أرض للإيجار مناسبة لمشاريع سياحية مؤقتة",
    yearBuilt: null,
    amenities: [],
    type: "أرض",
    agent: employerCompanies[1],
    rentalTerm: "شهري",
    dayRent: 1000,
    weeklyRent: 6500,
    monthlyRent: 20000,
    yearlyRent: 220000,
    address: "التجمع الخامس، القاهرة الجديدة، القاهرة",
    purpose: "بيع",
    details: {
      bedrooms: 5,
      bathrooms: 4,
      area: 320,
      parking: 2,
      yearBuilt: 2020,
    },

    videos: [
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
    ],
    construction: "جاهز",
    furnishing: "مفروشة",
    createdAt: "2025-07-01T14:20:00Z",
    reference_num: "بيوت - christine-masaya",
  },
  {
    id: "9",
    title: "شقة للإيجار في مدينة نصر",
    location: {
      lat: 31.0419,
      lng: 29.7433,
      address: "بورتو مارينا، الإسكندرية، مصر",
    },
    nearbyPlaces: [
      {
        id: "1",
        name: "مدرسة بورتو مارينا الدولية",
        type: "school",
        distance: "1.2 كم",
        location: [31.0425, 29.745],
      },
      {
        id: "2",
        name: "مطعم البحر الأحمر",
        type: "restaurant",
        distance: "0.2 كم",
        location: [31.0415, 29.744],
      },
      {
        id: "3",
        name: "مستشفى مارينا الدولي",
        type: "hospital",
        distance: "3 كم",
        location: [31.045, 29.75],
      },
      {
        id: "4",
        name: "سوق بورتو",
        type: "market",
        distance: "0.3 كم",
        location: [31.041, 29.743],
      },
      {
        id: "5",
        name: "شاطئ بورتو",
        type: "beach",
        distance: "0.1 كم",
        location: [31.0418, 29.7445],
      },
    ],
    area: 120,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://images.bayut.eg/thumbnails/27844164-800x600.webp",
      "https://images.bayut.eg/thumbnails/27844166-800x600.webp",
    ],
    status: "مميز",
    description: "شقة للإيجار مفروشة بالكامل بالقرب من المواصلات والخدمات",
    yearBuilt: 2015,
    amenities: ["جراج", "أمن 24 ساعة"],
    type: "شقة",
    agent: employerCompanies[0],
    rentalTerm: "شهري",
    dayRent: 450,
    weeklyRent: 2800,
    monthlyRent: 9000,
    yearlyRent: 100000,
    address: "التجمع الخامس، القاهرة الجديدة، القاهرة",
    purpose: "بيع",
    details: {
      bedrooms: 5,
      bathrooms: 4,
      area: 320,
      parking: 2,
      yearBuilt: 2020,
    },

    videos: [
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
      "https://www.youtube.com/watch?v=0Uauw7LDAa4",
    ],
    construction: "جاهز",
    furnishing: "مفروشة",
    createdAt: "2025-07-01T14:20:00Z",
    reference_num: "بيوت - christine-masaya",
  },
];
